version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-latest"
sphinx:
  configuration: documentation/conf.py
  fail_on_warning: false
conda:
  environment: documentation/environment.yml
formats: []
